version: '3.8'
services:
  app:
    image: testingapplication_app
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_URL=${API_URL}
      - DATABASE_URL=${DATABASE_URL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - PUBLIC_APP_URL=${PUBLIC_APP_URL}
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm start"

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=maps17171
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
