version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_URL=http://5.35.126.251:3000
      - DATABASE_URL=postgresql://postgres:maps17171@db:5432/postgres?schema=public
      - SMTP_USER=pavelgrinevitsch2018@gmail.com
      - SMTP_PASS=jtbg zodq mtfc wrdm
      - PUBLIC_APP_URL=http://5.35.126.251:3000
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm start"

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=maps17171
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
