export const mockUsers = [
  {
    id: 1,
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    password: 'hashed_password_1',
    jobTitle: 'Software Engineer',
    createdAt: '2025-02-19T12:00:00Z',
    companyId: 2,
    role: 'USER',
    projects: [],
  },
  {
    id: 2,
    name: 'Bob Smith',
    email: 'bob.smith@example.com',
    password: 'hashed_password_2',
    jobTitle: 'Product Manager',
    createdAt: '2025-02-19T12:01:00Z',
    companyId: 2,
    role: 'USER',
    projects: [],
  },
  {
    id: 3,
    name: 'Charlie Brown',
    email: 'charlie.brown@example.com',
    password: 'hashed_password_3',
    jobTitle: 'UI/UX Designer',
    createdAt: '2025-02-19T12:02:00Z',
    companyId: 2,
    role: 'USER',
    projects: [],
  },
  {
    id: 4,
    name: 'David Miller',
    email: 'david.miller@example.com',
    password: 'hashed_password_4',
    jobTitle: 'DevOps Engineer',
    createdAt: '2025-02-19T12:03:00Z',
    companyId: 2,
    role: 'USER',
    projects: [],
  },
  {
    id: 5,
    name: 'Emma Davis',
    email: 'emma.davis@example.com',
    password: 'hashed_password_5',
    jobTitle: 'Data Analyst',
    createdAt: '2025-02-19T12:04:00Z',
    companyId: 2,
    role: 'USER',
    projects: [],
  },
  {
    id: 6,
    name: 'Frank Wilson',
    email: 'frank.wilson@example.com',
    password: 'hashed_password_6',
    jobTitle: 'QA Engineer',
    createdAt: '2025-02-19T12:05:00Z',
    companyId: 2,
    role: 'USER',
    projects: [],
  },
  {
    id: 7,
    name: 'Grace Lee',
    email: 'grace.lee@example.com',
    password: 'hashed_password_7',
    jobTitle: 'HR Manager',
    createdAt: '2025-02-19T12:06:00Z',
    companyId: 2,
    role: 'USER',
    projects: [],
  },
  {
    id: 8,
    name: 'Henry Clark',
    email: 'henry.clark@example.com',
    password: 'hashed_password_8',
    jobTitle: 'Marketing Specialist',
    createdAt: '2025-02-19T12:07:00Z',
    companyId: 2,
    role: 'USER',
    projects: [],
  },
  {
    id: 9,
    name: 'Isabel Turner',
    email: 'isabel.turner@example.com',
    password: 'hashed_password_9',
    jobTitle: 'Customer Support',
    createdAt: '2025-02-19T12:08:00Z',
    companyId: 2,
    role: 'USER',
    projects: [],
  },
  {
    id: 10,
    name: 'Jack White',
    email: 'jack.white@example.com',
    password: 'hashed_password_10',
    jobTitle: 'Business Analyst',
    createdAt: '2025-02-19T12:09:00Z',
    companyId: 2,
    role: 'USER',
    projects: [],
  },
];
